#version = 0.1

[default.deploy]
profile = "deploy-ci"
region = "${AWS_REGION}"
stack_name = "project1-data-qc"
s3_bucket = "${PACKAGING_BUCKET}"
s3_prefix = "project1-data-qc"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
parameter_overrides = "InputBucketName=${INPUT_BUCKET}"
